// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} max-w-7xl mx-auto h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }




import localFont from 'next/font/local';
import './globals.css';
import Navbar from '@/components/Navbar';

const lexie = localFont({
  src: [
    { path: '../../public/fonts/LexieReadable-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/LexieReadable-Bold.ttf', weight: '700', style: 'normal' },
  ],
  variable: '--font-lexie', // This links to Tailwind
});

const openDyslexic = localFont({
  src: [
    { path: '../../public/fonts/OpenDyslexic-Regular.otf', weight: '400', style: 'normal' },
    { path: '../../public/fonts/OpenDyslexic-Italic.otf', weight: '400', style: 'italic' },
    { path: '../../public/fonts/OpenDyslexic-Bold.otf', weight: '700', style: 'normal' },
    { path: '../../public/fonts/OpenDyslexic-BoldItalic.otf', weight: '700', style: 'italic' },
  ],
  variable: '--font-open', // This links to Tailwind
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${lexie.variable} ${openDyslexic.variable} font-lexie`}>
      <Navbar/>
      <body>{children}</body>
    </html>
  );
}